#!/bin/bash
# 浏览器测试指引

echo "🌐 浏览器测试步骤"
echo "==============================================="
echo ""
echo "1. 打开浏览器访问: http://localhost:8000"
echo ""
echo "2. 测试快速拒绝功能:"
echo "   - 模板图片: 选择 test_images/signature_template.png"
echo "   - 待验证图片: 选择 test_images/seal_template.png"
echo "   - 点击 '开始验证'"
echo ""
echo "3. 应该看到:"
echo "   ✓ 大标题显示 '0.0%'"
echo "   ✓ 验证类型: '手写签名 · ⚡ 快速拒绝'"
echo "   ✓ 算法模型: '⚡ 笔画筛选器'"
echo "   ✓ 处理时间: ~25ms"
echo "   ✓ 漂亮的特征对比表格"
echo "   ✓ 黄色拒绝原因框"
echo "   ✓ 蓝色说明框"
echo ""
echo "4. 测试正常验证:"
echo "   - 模板图片: test_images/signature_template.png"
echo "   - 待验证图片: test_images/signature_real.png"
echo "   - 应该通过笔画筛选,进入深度学习验证"
echo "   - 显示相似度 ~95%"
echo ""
echo "5. 打开浏览器开发者工具(F12)"
echo "   - 查看 Console 标签"
echo "   - 应该看到详细的验证日志"
echo "   - 包含 '📊 验证结果:' 的完整数据"
echo ""
echo "==============================================="
echo ""
echo "📱 服务地址: http://localhost:8000"
echo "🔍 API文档: http://localhost:8000/docs"
echo ""
