#!/bin/bash
# 快速测试清洁图片展示功能

echo "🎨 签名清洁图片展示功能 - 测试指南"
echo "========================================"
echo ""
echo "✅ 功能已部署！"
echo ""
echo "📋 测试步骤："
echo ""
echo "1️⃣  打开浏览器访问:"
echo "   🌐 http://localhost:3000"
echo ""
echo "2️⃣  上传两张裁剪的签名图片"
echo "   📁 选择 '手写签名' 模式"
echo "   📤 上传模板签名"
echo "   📤 上传查询签名"
echo ""
echo "3️⃣  点击 '开始验证' 按钮"
echo "   ⏳ 等待处理（约1-2秒）"
echo ""
echo "4️⃣  查看验证结果区域"
echo "   📊 相似度、欧氏距离等指标"
echo "   🧹 **新增：签名清洁效果对比**"
echo "      - 左图：模板清洁结果"
echo "      - 右图：查询清洁结果"
echo "      - 显示清洁模式 (conservative/aggressive)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 预期看到的内容："
echo ""
echo "验证结果区域会显示:"
echo "┌─────────────────────────────────┐"
echo "│ 验证结果                         │"
echo "│ 相似度: XX%                      │"
echo "│ ···                             │"
echo "├─────────────────────────────────┤"
echo "│ 🧹 签名清洁效果对比              │"
echo "│ ┌──────────┐  ┌──────────┐     │"
echo "│ │ 模板清洁  │  │ 查询清洁  │     │"
echo "│ │   结果   │  │   结果   │     │"
echo "│ └──────────┘  └──────────┘     │"
echo "│ 清洁模式: conservative           │"
echo "└─────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 对比要点："
echo ""
echo "原始图片 vs 清洁后图片："
echo "  • 表格线 → 应被移除 ✓"
echo "  • 背景噪点 → 应被移除 ✓"
echo "  • 签名笔画 → 应完整保留 ✓"
echo "  • 图像更纯净 → 只有黑色笔画 + 白色背景"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🐛 故障排查："
echo ""
echo "如果看不到清洁图片:"
echo ""
echo "1. 检查浏览器控制台 (F12)"
echo "   - 看是否有图片加载错误"
echo "   - 检查网络请求状态"
echo ""
echo "2. 检查后端日志"
echo "   tail -f backend/backend.log"
echo "   - 确认 debug_images 字段有值"
echo ""
echo "3. 检查 debug 目录"
echo "   ls -lh backend/uploaded_samples/debug/"
echo "   - 确认图片已生成"
echo ""
echo "4. 手动访问图片"
echo "   http://localhost:8000/uploaded_samples/debug/template_cleaned_xxx.png"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📸 保存测试结果："
echo ""
echo "清洁后的图片自动保存在:"
echo "  📂 backend/uploaded_samples/debug/"
echo "     ├── template_cleaned_YYYYMMDD_HHMMSS.png"
echo "     └── query_cleaned_YYYYMMDD_HHMMSS.png"
echo ""
echo "可以下载这些图片进行详细对比分析。"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 关键功能点："
echo ""
echo "✅ 前端显示: 实时展示清洁后的图片"
echo "✅ 后端存储: 自动保存 debug 图片"
echo "✅ 静态服务: /uploaded_samples 路径访问"
echo "✅ CORS支持: 跨域访问无阻碍"
echo "✅ 智能显示: 只在签名+启用清洁时显示"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 现在开始测试吧！"
echo ""
echo "访问: http://localhost:3000"
echo ""
